dist: trusty
sudo: required

env:
  - COREOS_TRACK=stable OS_VERSION=1235.9.0
  - COREOS_TRACK=stable OS_VERSION=1235.12.0  
  - COREOS_TRACK=stable OS_VERSION=current

before_script:
  - curl https://${COREOS_TRACK}.release.core-os.net/amd64-usr/${OS_VERSION}/version.txt -o version.txt
  - cat version.txt
  - export $(cat version.txt | xargs)
  - if [ "$TRAVIS_EVENT_TYPE" != "push" ]; then
      curl -s https://hub.docker.com/v2/repositories/${DOCKER_USERNAME}/coreos-developer/tags/?page_size=10000 | 
      jq -e "[.results | .[] | .name == \"${COREOS_VERSION}\"] | any | not" || 
      travis_terminate 0;
    fi

script:
  - curl -L https://${COREOS_TRACK}.release.core-os.net/amd64-usr/${COREOS_VERSION}/coreos_developer_container.bin.bz2 -o coreos_developer_container.bin.bz2
  - bunzip2 -k coreos_developer_container.bin.bz2
  - mkdir ${COREOS_VERSION}
  - sudo mount -o ro,loop,offset=2097152 coreos_developer_container.bin ${COREOS_VERSION}
  - sudo tar -cp --one-file-system -C ${COREOS_VERSION} . | docker import - ${DOCKER_USERNAME}/coreos-developer:${COREOS_VERSION}

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push ${DOCKER_USERNAME}/coreos-developer:${COREOS_VERSION}

jobs:
  include:
    - stage: trigger
      script:
        - gem install travis --no-rdoc --no-ri
        - travis login --org --skip-completion-check --no-manual --explode --github-token=${GITHUB_TOKEN}
        - token=$(travis token --org --skip-completion-check --no-interactive)
        - |
          curl -s -X POST \
            -H "Content-Type: application/json" \
            -H "Accept: application/json" \
            -H "Travis-API-Version: 3" \
            -H "Authorization: token ${token}" \
            -d "{ \"request\": { \"branch\":\"master\" }}" \
            https://api.travis-ci.org/repo/zazrivec/coreos-nvidia-driver/requests
